export const tableModelE = {
  heading: [
    { content: `Критерії аналогії` },
    { content: `Э<sub>1</sub>` },
    { content: `Э<sub>2</sub>` },
    { content: `Э<sub>3</sub>` },
    { content: `Э<sub>4</sub>` },
    { content: `Э<sub>5</sub>` },
    { content: `Э<sub>ij</sub>` },
  ],
  row: [
    [
      { content: `K<sub>11</sub>` },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
    ],
    [
      { content: `K<sub>12</sub>` },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
    ],
    [
      { content: `K<sub>13</sub>` },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
    ],
    [
      { content: `K<sub>14</sub>` },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
    ],
    [
      { content: `K<sub>15</sub>` },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
    ],
    [
      { content: `K<sub>16</sub>` },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
    ],
    [
      { content: `K<sub>21</sub>` },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
    ],
    [
      { content: `K<sub>22</sub>` },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
    ],
    [
      { content: `K<sub>23</sub>` },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
    ],
    [
      { content: `K<sub>31</sub>` },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
    ],
    [
      { content: `K<sub>51</sub>` },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
    ],
  ]
};
