export const tableModelMN = {
  heading: [
    { content: `` },
    { content: `A<sub>1</sub>` },
    { content: `A<sub>2</sub>` },
    { content: `A<sub>3</sub>` },
    { content: `A<sub>4</sub>` },
    { content: `A<sub>5</sub>` },
    { content: `A<sub>6</sub>` },
  ],
  row: [
    [
      { content: `A<sub>1</sub>` },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
    ],
    [
      { content: `A<sub>2</sub>` },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
    ],
    [
      { content: `A<sub>3</sub>` },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
    ],
    [
      { content: `A<sub>4</sub>` },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
    ],
    [
      { content: `A<sub>5</sub>` },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
    ],
    [
      { content: `A<sub>6</sub>` },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
      { content: ``, editable: true },
    ],
  ]
};
